coverage:
  precision: 2
  round: down

ignore:
  - "cmd/**"
  - "internal/core/ports/**"
  - "internal/testhelpers/**"
  - "migrations/**"
  - "**/*_test.go"
  - "internal/adapters/repositories/gorm_adapter.go"